export const StaffTypeListAT = {
  REQUEST: "STAFF_TYPE_LIST_REQUEST",
  SUCCESS: "STAFF_TYPE_LIST_SUCCESS",
  FAIL: "STAFF_TYPE_LIST_FAIL",
};

export const RoleTypeListAT = {
  REQUEST: "ROLE_TYPE_LIST_REQUEST",
  SUCCESS: "ROLE_TYPE_LIST_SUCCESS",
  FAIL: "ROLE_TYPE_LIST_FAIL",
};

export const SalutationListAT = {
  REQUEST: "SALUTATION_LIST_REQUEST",
  SUCCESS: "SALUTATION_LIST_SUCCESS",
  FAIL: "SALUTATION_LIST_FAIL",
};

export const TeamMemberFormAT = {
  DEFAULT: "TEAM_MEMBER_FORM_DEFAULT",
  CHANGE: "TEAM_MEMBER_FORM_CHANGE",
};

export const CompanyAT = {
  GET_REQUEST: "GET_COMPANY_REQUEST",
  GET_SUCCESS: "GET_COMPANY_SUCCESS",
  GET_FAIL: "GET_COMPANY_FAIL",
  EDIT_REQUEST: "EDIT_COMPANY_REQUEST",
  EDIT_SUCCESS: "EDIT_COMPANY_SUCCESS",
  EDIT_FAIL: "EDIT_COMPANY_FAIL",
};