export const StaffTypeListAT = {
  REQUEST: "STAFF_TYPE_LIST_REQUEST",
  SUCCESS: "STAFF_TYPE_LIST_SUCCESS",
  FAIL: "STAFF_TYPE_LIST_FAIL",
};

export const RoleTypeListAT = {
  REQUEST: "ROLE_TYPE_LIST_REQUEST",
  SUCCESS: "ROLE_TYPE_LIST_SUCCESS",
  FAIL: "ROLE_TYPE_LIST_FAIL",
};

export const SalutationListAT = {
  REQUEST: "SALUTATION_LIST_REQUEST",
  SUCCESS: "SALUTATION_LIST_SUCCESS",
  FAIL: "SALUTATION_LIST_FAIL",
};
